version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map container's port 80 to host's port 8080 (or any desired port)
    volumes:
      - .:/var/www/html # Mount the Laravel application code into the container
    depends_on:
      - db # Ensure the 'db' service (PostgreSQL) is started before the 'app' service

  db:
    image: postgres:latest # Use the latest PostgreSQL image
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432" # Map container's port 5432 to host's port 5432 (or any desired port)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data across container restarts
  gui:
    build:
      context: views
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
volumes:
  postgres_data: 
    driver: local
