name: Assign to Samnoon

on:
  issues:
    types: [opened]
jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto-assign Issue
        uses: pozil/auto-assign-issue@v1.11.0

        with:
          assignees: samnoon1971
          allowSelfAssign: true
